### ISSUE TITLE
Analysis/ tree building breaks on custom entered property of cells

### ISSUE THREAD

**Issue by annastoeckl** [Schwartz-AlaLaurila-Labs/sa-labs-analysis-core#1]
I entered the following property to the cell properties in Symphony during recordings:  'Loc Amp1' with [x y]. But it seems the tree builder cannot handle it. When I delete the property (or store it under Keywords or Notes) tree building works fine

Invalid field name: 'Loc Amp1'.

Error in sa_labs.analysis.entity.FeatureGroup/addParameter (line 277)
            obj.parameters.(property) = value;

Error in sa_labs.analysis.entity.FeatureGroup/setParameters (line 165)
                    obj.addParameter(names{i}, parameters(names{i}));

Error in sa_labs.analysis.core.OfflineAnalysis/setEpochParameters (line 144)
                featureGroups(i).setParameters(data.getPropertyMap());

Error in sa_labs.analysis.core.OfflineAnalysis/copyEpochParameters (line 71)
                obj.setEpochParameters(featureGroup);

Error in sa_labs.analysis.core.OfflineAnalysis/add (line 129)
                obj.copyEpochParameters(featureGroup);

Error in sa_labs.analysis.core.OfflineAnalysis/add (line 127)
                    obj.add(id, epochGroup, params(2 : end));

Error in sa_labs.analysis.core.OfflineAnalysis/add (line 127)
                    obj.add(id, epochGroup, params(2 : end));

Error in sa_labs.analysis.core.OfflineAnalysis/build (line 41)
                obj.add(obj.DEFAULT_ROOT_ID, epochGroup, parameters);

Error in sa_labs.analysis.core.Analysis/service (line 41)
            obj.build();

Error in sa_labs.analysis.app.OfflineAnalaysisManager/buildAnalysis (line 165)
                    analysis.service();

Error in buildAnalysis (line 4)
offlineAnalysisManager.buildAnalysis(projectName, presets);

**Comment by ragavsathish** [comment]
Requires changes in FeatureGroup : [addParameter](https://github.com/Schwartz-AlaLaurila-Labs/sa-labs-analysis-core/blob/master/src/main/matlab/%2Bsa_labs/%2Banalysis/%2Bentity/FeatureGroup.m#L276) to make a valid parameter name. 

Probable fix - `matlab.lang.makeValidName('param name') >> paramName`
