### ISSUE TITLE
Problem with parameters when 2 amplifier leafs are combined

### ISSUE THREAD

**Issue by annastoeckl** [Schwartz-AlaLaurila-Labs/sa-labs-analysis-core#5]
When two or more amplifiers are combined, the stimuli parameters from each individual amplifier are "added up", i.e. if there are 10 epochs, there will be 20 parameters if 2 amplifiers are combined (presumable 40 with 4). While there should actually be just 10. 
So when combining leafs there needs to be an exception for amplifiers, to not add up parameters (at least relating to stimuli, parameters relating to individual amplifiers should all be kept).

**Comment by ragavsathish** [comment]
Fixed #12
